### ISSUE TITLE
Actualize develop-branch

### ISSUE THREAD

**Issue by ZXeRRinor** [ghachey/pacific-emis-education-survey-tool#11]
Upload commits with last bugfixes.
[Actual branch](https://github.com/ZXeRRinor/pacific-emis-education-survey-tool/commits/actualize_develop_branch)

**Comment by ghachey** [comment]
There is no need to create issues for the pull request when submitted code. Issues are created for new featutes (labelled enhancement) and bugs (labelled bug). Developers can create PR for individual issues when they are ready and not wait for large amount of work to sync into the official repository.
