### ISSUE TITLE
List of grades options incorrect

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-emis-education-survey-tool#17]
The following list of grades is incorrect.

![question-for-weison](https://user-images.githubusercontent.com/1091769/120951432-6091ba00-c77b-11eb-9429-2dbcdb0667bc.png)

It must be urgently changed to

- Grade ECE
- Grade 1
- Grade 2
- Grade 3
- Grade 4
- Grade 5
- Grade 6
- Grade 7
- Grade 8
- Grade 9
- Grade 10
- Grade 11
- Grade 12

Note that this list will also soon have to be dynamically retrieved from the API as per the new requirement described in https://github.com/ghachey/pacific-emis-education-survey-tool/issues/15

**Comment by ZXeRRinor** [comment]
Created and completed task NDOE-230 for this issue.
