### ISSUE TITLE
Deleting the cloudfile should delete it on the tablet

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-emis-education-survey-tool#24]
Is this scenario feasible. When a cloudfile is deleted from the cloud service account from the EMIS web app it would also delete it from the tablet(s) where it resides.

This would make file management in the cloud easier.

**Comment by maratomega** [comment]
Hi @ghachey do we need to notify the user? Or there no need to show this pop up Note/error/etc.
![Screenshot_20220804_092712_org pacific_emis surveys](https://user-images.githubusercontent.com/108275362/182780510-c59f9df0-af05-4216-be40-adb3d0665d3b.jpg)

**Comment by ghachey** [comment]
I do not understand this pop-up and how it relates to this feature. Can you explain further what you are asking please?

**Comment by maratomega** [comment]
This is related to the inability to delete the survey from the device that was deleted in the cloud because there is no Internet connection. The question is whether to notify the user or not

**Comment by maratomega** [comment]
CReate new screen Logs, to keep the record of deleted surveys

**Comment by maratomega** [comment]
![Main screen Survey](https://user-images.githubusercontent.com/108275362/184822868-9482a67f-78b6-4f7a-a36e-8d3b31474bd2.PNG)
![Logs with email](https://user-images.githubusercontent.com/108275362/184822938-77dd3b2d-27fc-4cb4-a3ab-d90c9afa220b.PNG)
![Logs no email](https://user-images.githubusercontent.com/108275362/184822955-a04647ea-cb7f-41b5-b234-4fae32e720e7.PNG)

The design of Logs screen is ready, please review the icon on the Main screen, and the actual Logs screen, we have prepared 2 versions, 1 with email, 2 without email, which one do you want to go with?

**Comment by ghachey** [comment]
@maratomega The screens look good. However, it would be good to have a column with the description of the action. For example, "Delete" or in the future will log other actions as well such as "Created", "Edited", etc. But as it is it does not convey enough details.

**Comment by maratomega** [comment]
> he screens look good. However, it would be good to have a column with the description of the action. For example, "Delete" or in the future will log other actions as well such as "Created", "Edited", etc. But as it is it does not convey enough details.

Can you please point where you would like to see that Column?

Also, please clarify, do we need to show email or there no need for that?

**Comment by ghachey** [comment]
@maratomega Yes, the email (user) should be shown. Just the user who created the survey. Put the action as the last column.

**Comment by maratomega** [comment]
![pdated Logs](https://user-images.githubusercontent.com/108275362/185073374-085da373-5250-4701-9deb-ade84282c8a1.PNG)
Updated Logs screen, with Deleted column

**Comment by ghachey** [comment]
That's a perfect started point.

**Comment by maratomega** [comment]
Hi @ghachey 
on our new Logs screen at the moment we use the Date of creation of the Survey, should it be changed to the date of the activity (when survey was deleted)?
Plus, what do you think about adding the additional functionality to Logs screen - the ability to view the info about certain activity by tapping on it?

**Comment by ghachey** [comment]
@maratomega 

- Date of creation for creation of survey is correct already. 
- New functionality in the log as proposed is a good idea but not a priority at the moment.

**Comment by ghachey** [comment]
@maratomega The delete from cloud seems to work only in the Development mode. In Development mode I can go and delete a cloufile and it will successfully delete it from the tablet and add the Delete record to the Log. However, if I am in Production mode this does not happen.

**Comment by ghachey** [comment]
Has the requested been implemented? Seems not.

![Screenshot 2022-11-22 145812](https://user-images.githubusercontent.com/1091769/203246349-bf2fe817-16ad-48ed-b453-573eebfb0800.jpg)

I do not see the new setting in the app nor is the value in the firebase used.

**Comment by ghachey** [comment]
This seems to be working in latest build.
