### ISSUE TITLE
Include the tablet ID  or name into the cloud file meta data

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-emis-education-survey-tool#33]

**Comment by maratomega** [comment]
Hi @ghachey could you share more information about this issue

**Comment by ghachey** [comment]
Hi @maratomega . The idea here is to add a tiny bit of data to assist in troubleshooting the duplicate issue we are struggling to fix. So this is a proposed work to assist with issue #21 .

Refer to the screenshot below. On the left is the metadata of a Google Service Cloudfile. On the right is our XML Survey. I propose we add some tablet unique identifyer of some sort. Let's call it "sourceTabletIdentifyier". This would be a value taken from the tablet this cloud file is coming from. This could be the name? an ID on Android? anything unique to the tablets. I think it can be only on the metadata properties (as on the left of image below). But I don't think it would not hurt to have it also on the XML survey file.

<img width="683" alt="Screenshot 2022-07-04 104634" src="https://user-images.githubusercontent.com/1091769/177168600-0293f964-ddc3-487f-9f9f-1a2159c47ac1.png">

So of course in merging this value is not carried over. For example, merging a worker tablet (device 2) into a team leader's tablet (device 1) the sourceTabletIdentifyer from device 2 will not make it to device 1.

Let me know if you come across anything you are not sure.

**Comment by maratomega** [comment]
Hi @ghachey perhaps instead of adding tablet ID, we can use lastEditedUser to identify the tablet? To avoid adding new metadata (tablet ID)

**Comment by maratomega** [comment]
One more question about Status of survey: right now we have the following flow - the Positive survey when it's merged gets new status Merged, we think it's a bug, and it should keep the same status Positive. 
Correct me if I'm wrong.

**Comment by ghachey** [comment]
> One more question about Status of survey: right now we have the following flow - the Positive survey when it's merged gets new status Merged, we think it's a bug, and it should keep the same status Positive. Correct me if I'm wrong.

What is this use case scenario you have discovered? I believe this could possibly be responsible for the duplicate and is related to issue #34 and #21 which is the original bug issue. Let's get this cleared up. Are you saying that a survey with surveyCompleted=POSITIVE can actually get merged and then switch to MERGED status? If this is what you have then yes, this is definitely an issue. Because when a survey has surveyCompleted=POSITIVE this means is it completed and thus there is no reason to merge this anywhere. Refer to my comment https://github.com/ghachey/pacific-emis-education-survey-tool/issues/34#issuecomment-1173867772

But your assumption that it "should be kept the same status POSITIVE" is not quite the correct handling of this. Because a survey with surveyCompleted=POSITIVE is considered completed and ready for review online and approval. No more merging of this should be allowed. Refer back to my comment linked in above paragraph.

**Comment by maratomega** [comment]
Hi @ghachey A survey is created and assigned a tablet id. When a user (the same email) opens and edits a survey from another device, his tablet id should be copied (replaced with the current one) or the id of the tablet is added to the previous one? The same applies to other users who edit or merge a survey. If the user will be different (other email), but the device is one, what should happen to id in the survey?

From Google guides: the tablet id is a unique application installation identifier. If the application is removed from the device and reinstalled, the id will change. The above scenario is based on the advice of Google to avoid problems in the future.

**Comment by ghachey** [comment]
I'm not sure I am following this. Perhaps can you re-phrase it in the familiar context scenarios (i.e. team leader device 1, worker device 2, 3, 4, etc.)

**Comment by ghachey** [comment]
This seems all good.
