### ISSUE TITLE
Prevent merging into one that was already merged

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-emis-education-survey-tool#34]

**Comment by ghachey** [comment]
Taken from #21 this proposed work may help in reducing/eliminating the duplicate cloud files error. It consists in eliminating the user process error where they may be tempted to merge tablets in both directions. The comments was originally in #21 but moved here as a new related small piece of work.

----

Once you have a Completed survey there is no need to merge into another one. It is already completed and is usually done into the team leader's tablet (device 1). We have a completed survey (in device 1) and that will be the official one that will be processed into the system. All the workers' tablets (device 2, 3, 4, etc.) merge into the team leader's tablet (device 1). It is a one way only thing. When they (the workers tablet or device 2, 3, 4) have merged their content they become in status MERGED (from a previous in progress status). And it should not be possible to merge something else into this worker tablet (merging back the completed device 1 into device 2 in merged state should be refused with the following message.

"This tablet was already used as a worker tablet and was already merged into the team leader's tablet. You do not need and can not merge anything back here. You can merge again into the team leader's tablet if you really need to, but any final adjustments can simply be done in the team leader's tablet also."

The MERGED status is final. The only thing that would be acceptable would be that the same worker could re-merge into the team leader again (for example if they worker updated something and would want to push updates to team leader tablet. But this scenario is not too important as any final update could be done simply on the team leader's tablet also.)

Here the tablet app is already behaving almost perfectly. Please any improvement is welcome (and desired) but MUST be done with care as I do not want to introduce any issue. So please make sure everything is perfectly clear before any change. And it must be tested into its own branch thoroughly.

**Comment by maratomega** [comment]
Hi @ghachey perhaps instead of adding tablet ID, we can use lastEditedUser to identify  the tablet? To avoid adding new metadata (tablet ID)

**Comment by maratomega** [comment]
Hi @ghachey 
Please advise:
1) Positive status - (can't be merged) when selected user get an error with the text: "This survey is completed" button "ok"

2) The MERGED status we allow merging - user sees the pop-up when selects it with the text: "This survey was already merged. Would you like to merge it again?"
Buttons "Cancel" and "Merge" or "Cancel" and "ok"

3) NEGATIVE status is unchanged

**Comment by ghachey** [comment]
@maratomega Yes.

**Comment by ghachey** [comment]
@maratomega We need to review the 1. above. I misunderstood what you meant and the current behavior in latest build is not desired.

**Comment by ghachey** [comment]
From my testing with latest build this seems to be working as desired. Will observe again in production and file a new issue if ever an issue is encountered
