### ISSUE TITLE
A place to record the principal's name

### ISSUE THREAD

**Issue by maratomega** [ghachey/pacific-emis-education-survey-tool#37]
New functionality/Field/data ?

**Comment by ghachey** [comment]
This is just enabling a field that is already there when the survey is complete in the report page. Make this editable and can automatically populate from the list of teachers like it is possible with the WASH Survey.

<img width="384" alt="Screenshot_20220727-223440" src="https://user-images.githubusercontent.com/1091769/184048985-db872ef8-0462-4e91-b47a-051751dc0239.png">

**Comment by ghachey** [comment]
This seems to be working.

**Comment by ghachey** [comment]
Will close with the PR
