### ISSUE TITLE
UI changes suggestion [proposed Label] enhancement

### ISSUE THREAD

**Issue by maratomega** [ghachey/pacific-emis-education-survey-tool#43]
@ghachey 
We have a suggestion, the Menu icon  (3 screens: 1) School Accreditation; 2) Water, Sanitation and Hygiene; 3)Software License), on the top left corner, change to Go back arrow icon, cause it performs the same action - returning to previous screen
![Clipboard - 14 сентября 2022 г , 12_21](https://user-images.githubusercontent.com/108275362/190119855-2ca52ba9-1b95-4688-ac38-13f713d79b8f.png)

**Comment by maratomega** [comment]
This is the current design - Menu icon
![Screenshot 2022-09-15 at 14 01 20](https://user-images.githubusercontent.com/108275362/190389585-c04c8981-9a9b-47fe-81ca-31d8213cb8f3.png)



--------
This is what we suggest - Menu icon change to Go back arrow icon
![Screenshot 2022-09-15 at 14 09 34](https://user-images.githubusercontent.com/108275362/190389600-4e96c14b-3c0f-4b69-b079-f8f68610ef29.png)

**Comment by ghachey** [comment]
@maratomega yes ok.
