### ISSUE TITLE
Why are tablets showing twice when merging with Bluetooth

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-emis-education-survey-tool#44]
![Screenshot 2022-09-15 105744](https://user-images.githubusercontent.com/1091769/190303393-23096250-aa5e-4da6-9902-03c8bc4c58a4.jpg)

**Comment by ghachey** [comment]
@maratomega has this been investigated?

**Comment by maratomega** [comment]
Hi @ghachey still trying to replicate it.
Can you describe your steps?

**Comment by maratomega** [comment]
> Hi @ghachey still trying to replicate it. Can you describe your steps?

Conditions, device, OS version, etc.

**Comment by ghachey** [comment]
This is only happening on one of my tablets. It is the same tablet has the other ones. I can't really reproduce in any other way. Will close assuming this will not affect anybody else and is but an edge case. Can re-open if we observe on other people's tablet. It does not affect the merging feature, one can simply select one of the listed duplicated tablet for merging and it works fine.
