### ISSUE TITLE
School Accreditation empty space bug

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-emis-education-survey-tool#46]
What happened to school accreditation?

![Screenshot 2022-09-20 104816](https://user-images.githubusercontent.com/1091769/191156385-0b12b23f-3200-4252-b4d7-e7e6b119f9fd.jpg)

**Comment by maratomega** [comment]
@ghachey I think this belongs to Dashboards, fixed in the newest build, which we will share with you after making some adjustments (e.g.: https://github.com/ghachey/pacific-open-education-data/issues/22) and internal testing

**Comment by ghachey** [comment]
You you pointed out @maratomega this issue was created in the wrong place. It was created again in the right repository https://github.com/ghachey/pacific-open-education-data/issues/23

**Comment by ghachey** [comment]
Wrongly created refer to https://github.com/ghachey/pacific-open-education-data/issues/23
