### ISSUE TITLE
RMI Form B Report miscalculation

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-emis-education-survey-tool#56]
[this issue **ONLY** affect the RMI (MIEMIS) Form B report and **NOT** FSM (FedEMIS)]

There is a minor but important issue with how the Form B report is produced. Refer to below screenshot comparing the Tablet report versus the online MIEMIS web app. This one is in production but can be easily reproduced in Development.

![1044214762-Screenshot 2022-10-12 115915](https://user-images.githubusercontent.com/1091769/195287915-b1f0790b-5c64-4c1b-8eae-b80bb99e105a.jpg)

The final tally is the count of each Level (1, 2, 3 and 4) from all the school evaluation standards. Those seem to be counted correctly. However, the final result differ a little. I believe the difference is caused by how the final level for the two classroom observations are calculated. In RMI, the two classroom observations contribute to the final tally. For example, if classroom observation one is level 1 and classroom observation two is level 2 you would increment the tally of level 1 and level 2 by one to the final tally (hence the total of 26 and not 24 coming from the school evaluation standards). The tablet seems to be using the partition as shown in the legend to produce the final level of each classroom observations:

- Level 1 - 0-50%
- Level 2 - 51-75%
- Level 3 - 76-90%
- Level 4 - 91-100%

But this is incorrect. For the classroom observations you partition as follows (essentially 4 equal partitions for the 60 possible scores of a classroom observation):

- Level 1 - 0-15
- Level 2 - 16-30
- Level 3 - 31-45
- Level 4 - 46-60

So a couple of things to do here. First, in the Summary tab of the final report remove the legend as it does not apply in RMI as such.

![Screenshot 2022-10-12 162450](https://user-images.githubusercontent.com/1091769/195290798-dafdc4a5-6d67-4f01-9cd0-c9f62e462756.jpg)

Then add to the summary the final score for both classroom observations as shown below. The three areas highlighted in yellow are the string "Classroom Observation Final Score" the total summed correct answers of the classroom observation and the final score as defined by the partition above (the example below is a total of 35 score yes in the classroom observation which falls in Level 3 - 31-45).

![Screenshot 2022-10-12 163327](https://user-images.githubusercontent.com/1091769/195296100-0f4d6009-00e1-4c80-9cf5-799923cd87fb.jpg)

Finally, fixing the above I believe will then automatically fix the final tally shown below.

![Screenshot 2022-10-12 164247](https://user-images.githubusercontent.com/1091769/195295070-c7611972-041a-43e5-b1fe-188fb351eb8e.jpg)

**Comment by maratomega** [comment]
![RMI Report summary (1)](https://user-images.githubusercontent.com/108275362/196118630-8c6cf1d5-f12e-42b1-babb-15ed3c266f01.png)
 
The school used in the example of from FSM the design sample is for RMI Form B report only.

**Comment by ghachey** [comment]
I'd like to clarify the comment above. The screenshot uses a school from FSM. However, this design change from the Form B report only applies to RMI Form B report and will not change the FSM report. The adjusted design in the screenshot above is approved and, again, only applies to RMI version of the Form B report.

**Comment by ghachey** [comment]
This seems to be correct in the latest version. Can close when merging.
