### ISSUE TITLE
Review the rules that defines a survey to be completed

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-emis-education-survey-tool#69]
From Delihda:

> For example, what does it mean when a survey is "completed"? Is it just ticking a "yes" or a "no" or does it mean there is a comment, a photo, and having all the classroom observations be filled in?

Currently when all yes/no questions have been answered this is considered completed. However, FSM indicated they might want something a little more strict such as enforcing other data (photos, comments, etc.)

Need to review this with the team to see what change if anything is worth doing here.

**Comment by maratomega** [comment]
Hi @ghachey,
Kindly let us know what exactly do you want to add?

Do you want to add the new rules to all countries or to FSM only?

**Comment by ghachey** [comment]
@maratomega this is work for later this year. It will only be FSM.

**Comment by ghachey** [comment]
This is duplicate of #57
