### ISSUE TITLE
General updates

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-emis-education-survey-tool#70]
Do all updates on software dependencies, eliminate any warning/deprecation/etc and ensure a clean build that runs flawlessly on all modern phones.

**Comment by maratomega** [comment]
@ghachey  General updates relates to this https://github.com/ghachey/pacific-emis-education-survey-tool/issues/67

**Comment by ghachey** [comment]
> @ghachey General updates relates to this #67

Yes, it can definitely relate to this. If an update is required because of #67. But it is also more general in that any dependency that we can safely upgrade we should as part of standard on-going maintenance.

**Comment by ghachey** [comment]
@maratomega please share updates on this.

**Comment by maratomega** [comment]
@ghachey addressed
